[project]
name = "grafana-on-uv"
version = "0.1.0"
description = "Monadic Grafana Client"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grafana-client>=5.0.1",
    "returns>=0.26.0",
]

[tool.uv]
package = true
